---
      - name: "Install bind DNS Server"
        apt:
          name: "bind9"
          state: latest
        when: bind == "yes"

      - name: "Change default listener"
        replace: '{{ item }}'
        path: /etc/bind/named.conf.options
        with_items:
         - "/bin/sed -i 's|// forwarders {/ forwarders {|g' /etc/bind/named.conf.options"
         - "/bin/sed -i 's|// 	0.0.0.0;/ 	0.0.0.0|g' /etc/bind/named.conf.options"
         - "/bin/sed -i 's|// };/ };|g' /etc/bind/named.conf.options"
        when: bind == "yes"

# to do: change bind default listener with j2 templates
      - name: "Change default listener"
      
      - name: "Enable bind9 at boot"
        systemd:
          name: bind9
          state: restarted
          enabled: yes
        when: bind == "yes"

