---
  - name: "Add nginx stable repository to apt"
    apt_repository:
      repo: deb http://nginx.org/packages/ubuntu/ xenial nginx
      state: present

  - name: "Install Nginx Web Server"
    apt:
      name: nginx-full
      state: present
      update_cache: yes

  - name: "Remove nginx default virtual host"
    file:
      path: "/etc/nginx/sites-enabled/default"
      state: absent

  - name: "Enable nginx in systemd"
    systemd:
      name: nginx
      state: restarted
      enabled: yes

  - name: "Replace new nginx.conf"
    get_url:
      url: "http://files.dpvps.com/nginx.conf.txt"
      dest: "/etc/nginx/nginx.conf"
